site:
  title: Redpanda Docs
  start_page: ROOT:get-started:index.adoc
  url: http://localhost:5002
content:
  sources:
  - url: .
    branches: HEAD
  - url: https://github.com/redpanda-data/docs-site
    branches: main
    start_paths: [site-search, home, api, shared]
  - url: https://github.com/redpanda-data/documentation
    branches: [v/*, '!v/21.11']
ui:
  bundle:
    url: https://github.com/redpanda-data/docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
  extensions:
  - '@asciidoctor/tabs'
  - '@redpanda-data/docs-extensions-and-macros/macros/glossary'
  - '@redpanda-data/docs-extensions-and-macros/macros/config-ref'
  - '@redpanda-data/docs-extensions-and-macros/macros/helm-ref'
antora:
  extensions:
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/unlisted-pages'
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/add-global-attributes'
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/aggregate-terms'
  - require: '@redpanda-data/docs-extensions-and-macros/extensions/version-fetcher/set-latest-version'